[formatter]

[formatter.json]
command = "jq"
includes = ["*.json"]
options = ["-S"]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
includes = ["*.md", "*.toml", "*.yaml"]
options = ["--plugin", "prettier-plugin-toml", "--write"]

[formatter.rust]
command = "rustfmt"
includes = ["*.rs"]

[formatter.shell]
command = "shfmt"
includes = ["*.sh"]
options = ["-bn", "-ci", "-sr", "-i", "2", "-s", "-w"]
