# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
command = "./target/debug/alejandra"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
    "*.css",
    "*.html",
    "*.js",
    "*.json",
    "*.jsx",
    "*.md",
    "*.mdx",
    "*.scss",
    "*.ts",
    "*.yaml",
]

[formatter.shell]
command = "shfmt"
options = [
    "-bn", # binary ops like && and | may start a line
    "-ci", # switch cases will be indented
    "-sr", # redirect operators will be followed by a space
    "-i", "2",  # indent 2
    "-s",  # simplify the code
    "-w",  # write back to the file
]
includes = ["*.sh"]

