[formatter]

[formatter.nix]
command = "cargo"
includes = ["*.nix"]
options = ["run", "--"]

[formatter.prettier]
command = "prettier"
includes = ["*.json", "*.md", "*.toml", "*.yaml"]
options = ["--plugin", "prettier-plugin-toml", "--write"]

[formatter.rust]
command = "rustfmt"
includes = ["*.rs"]

[formatter.shell]
command = "shfmt"
includes = ["*.sh"]
options = ["-bn", "-ci", "-sr", "-i", "2", "-s", "-w"]
