name: PR
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
concurrency:
  cancel-in-progress: true
  group: ${{ github.actor }}
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Build
      uses: docker://alpine:latest
      with:
        args: pwd
    - run: |
        pwd
        ls
    - name: Build
      uses: docker://alpine:latest
      with:
        args: ls
    - name: Build
      uses: docker://nixos/nix
      with:
        args:
          nix build
          --extra-experimental-features flakes
          --extra-experimental-features nix-command
          --print-build-logs
          --verbose
