name: PR
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
concurrency:
  cancel-in-progress: true
  group: ${{ github.actor }}
jobs:
  pr:
    name: PR
    runs-on: self-hosted
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Coverage
      uses: docker://nixos/nix
      with:
        args: >
          bash -ex -c "
            nix \
            --extra-experimental-features flakes \
            --extra-experimental-features nix-command \
            profile install direnv

            direnv allow

            cargo tarpaulin
          "

    - name: Build and Test
      uses: docker://nixos/nix
      with:
        args: >
          nix
          --extra-experimental-features flakes
          --extra-experimental-features nix-command
          build
          --print-build-logs
