name: PR
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
concurrency:
  cancel-in-progress: true
  group: ${{ github.actor }}
jobs:
  test:
    container:
      image: ubuntu:latest
      options: --user 1
    runs-on: self-hosted
    steps:
    - name: Setup
      run: |
        apt update
        apt install nodejs
        mkdir -p /__e/node12/bin
        ln -s $(command -v node) /__e/node12/bin/node
    - name: Clone
      uses: actions/checkout@v1
    - name: Install Nix
      uses: cachix/install-nix-action@v15
    - name: Build
      run: |
        nix build --print-build-logs -v
