name: PR
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
concurrency:
  cancel-in-progress: true
  group: ${{ github.actor }}
jobs:
  test:
    container:
      image: nixos/nix:latest
    runs-on: self-hosted
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Build
      run: |
        nix build --print-build-logs -v
