name: Release
on:
  push:
    branches: [ main ]
jobs:
  release:
    env:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    name: Release
    runs-on: self-hosted
    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Build and Release
      uses: docker://nixos/nix
      with:
        args: >
          bash -ec "
            nix \
            --extra-experimental-features flakes \
            --extra-experimental-features nix-command \
            --extra-substituters 'http://172.17.0.1:5000?priority=1&trusted=1' \
            --extra-substituters 'https://alejandra.cachix.org?priority=100&trusted=1' \
            build \
            --print-build-logs

            nix-env -iA cachix -f https://cachix.org/api/v1/install

            cachix push --compression-level 9 alejandra result
          "
